# GitHub Sponsors 配置
# 这些是支持的赞助平台

# GitHub Sponsors 用户名（替换为你的 GitHub 用户名）
github: [leeguooooo]

# Patreon 用户名
# patreon: leeguooooo

# Open Collective 项目名
# open_collective: leeguooooo

# Ko-fi 用户名
# ko_fi: leeguooooo

# Buy Me a Coffee 用户名
# custom: ['https://www.buymeacoffee.com/leeguooooo']

# 支付宝/微信赞赏码（可以使用图片链接）
custom: ['https://prodsuppart-s3.suppart.app/artworkCover/IMG_1132_2025-10-17_02-35-15-204Z.JPG']

